version: '2'
services:
  sampleapp-app:
    image: sampleapp
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://sampleapp-postgresql:5432/SampleApp
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  sampleapp-postgresql:
    extends:
      file: postgresql.yml
      service: sampleapp-postgresql
